language: node_js
sudo: false
node_js: stable
addons:
  firefox: latest
  chrome: stable
dist: trusty

install:
  - npm i -g bower polymer-cli
  - npx polymer install
before_script:
  - npm i -g eslint eslint-config-google eslint-plugin-chai-expect eslint-plugin-html
  - npm run lint
script:
  - npm run test
  - if [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sauce; fi

notifications:
  email:
    on_success: never
    on_failure: always
