language: node_js
sudo: false
before_script:
- npm run lint
install:
- npm i -g polymer-cli
- npm i
- polymer install --variants
node_js: stable
addons:
  firefox: latest
  chrome: stable
  sauce_connect: true
script:
- polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
dist: trusty
env:
  global:
  - secure: >- gcs/T5x4BRmq1u7fdNwhToWEA3unzcsyey+fSyrJ+U47l/yVNhwtgsHd+xcXr5KpzyWIu6zMA+XiaR1v5wLfQPAREtmxujQpcHm9KjqFAYpIK06hpc+X1y7xHvGL/NHzK3uPqiRNXTfWsdijNOLDPQDCZrZM+2k63BUrjdjfHtUPnfmQwS6OtvSQa3vUn1Bpd4HXOBQdA3gBigNkRnoigwKjZ8QfHc2q+T7xl4elb0DOQ39eI4hgX+4dWne0A755pH7HFGlhQdCHteDarhL0WL7xzE3Fd197Ly5ggQpjvhWR7FgbHrgWpGEz5sDB4+RSN8+nO9V8YD0FWgAjwUgR4IEE18iGRKgWu0TdHpytj9p/qNzdfKMhE4Mb4urcHGokJWvNeQ46h7lNMh5WOdMgG6d/rW0FiyuXP8au6myNnIoBKH+bbaHHgqdLG4dqpr7spSddwYRZh1qsww31acjMn2CizxxylAGhPBkiss9mhMhfBmXaMDVuewZK1xPxUVcbgXWOpt52PKLmHG+wpFpmoGFFAoCwMAmIV7gv0mu1pVKgLuIETRN2GePG1cMeLKAFJWcshj5Epdh1MaICDA6xSUfzaLFH1d6nMPcdVAiZo/tRTFEarckfUtAW3aIqw+0lbz9TooAg3hLNBOw1DvPjs9Am+0Rc7se2W1CA2zsj6jg=
  - secure: >- QO+LxWAIQqxAqSxmMy5FLIVZhDzzgPlpu+qzgi8ZkChff4Z2k7BecfN5ygZVcTzHWNQFPQgqKp3slt0p9sW1pr69Xv6qZ54XBV34LTm9H1FnBvJ8fKUMXHwNAibGFQJ8d26iJDRM9YDgUCDBn4oqr40bXlCjbkW+7h9qe1P2su8KAN4gUsLAQIO0VU+Y7sTeetbOhd+i6ShGMT6gVbObdRtaDeEU87jEQTl6V0PT4Qr8FRjCq3/VoFfzms/RxNIc+uLsxxFqcNHPBTc+XfwBjovREI+A98T0r2uIO71Cod8Oo1njhd6g/HUAuYLTCuPYrT9UXG8OKw2Q7uPtOgmKoox1ed9Rk7zh18RWLwEmwaCEetNr+mt/375lbHkKUpnbYKRukndx3Y5rYdz/TO7LVqnJ/mJancfWIuz8mfqBssw4Cq8NNIyUzIhE9nQZ8rzv+MHkWWTMVo47fXpmZB6NYzNPlk8Lq3JlMJyol52qzlCganjmXeaMMJz2ecpKScWuF7ot9LRlD3ScDrQylYumJHXDQ3VRRwkB01LUsL0ca78zfOeqDTgiOm8wD4Rh+IqRQKsnDwB+01bjSjvDdNLS6tmCjEeXAItZgxvBtQJLeM8mbmYKRB3mBtJpe9VScMs9qEzjsf3Vh5+0/Jq6NeiUL8a7kiXEG4nR5LURtG6cMZA=
