language: node_js
sudo: false
before_script:
- npm run lint
install:
- npm i -g polymer-cli
- npm i
- polymer install --variants
node_js: stable
addons:
  firefox: latest
  chrome: stable
script:
- polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
dist: trusty
